eliminate non-testable function

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -25,7 +25,7 @@ done
 
 
 die() {
-	[ $# -gt 0 ] && echo "error: $@" >&2
+	[ $# -gt 0 ] && echo "*** error: $@" >&2
 	exit 1
 }
 
@@ -34,16 +34,25 @@ messag_fmt="%-50s"
 passed_fmt=" PASSED\n"
 failed_fmt="*FAILED* (expected '%s' but got '%s')\n"
 
-. $(dirname $0)/functions
+. $(dirname $0)/functions || die "could not source own implementation!"
 
 if [ -r $SHUT_SUITE ]; then
 	shut_suite_path=$(ensure_rel_path $SHUT_SUITE)
-	. $shut_suite_path
+	. $shut_suite_path || die "could not source test suite '$shut_suite_path'"
 	ntests=$(echo "$SHUT_TESTS" | wc -w)
-	echo "running "$ntests" test cases from '$SHUT_SUITE'"
+	echo "running "$ntests" test cases from '$shut_suite_path'"
+
+	if [ "$SHUT_TARGET" = "_self" ]; then
+		echo "testing own implementation"
+	else
+		shut_suite_dir=$(dirname $shut_suite_path)
+		shut_target_path="${shut_suite_dir}/${SHUT_TARGET}"
+		. $shut_target_path
+		echo "testing implementation in '$shut_target_path'"
+	fi
 	echo
 else
-	echo "*** could not read '$SHUT_SUITE'"
+	echo "*** could not read test suite '$SHUT_SUITE'"
 	exit 1
 fi
 
